language: java

jdk:
    - oraclejdk8

# Only ci these branches
branches:
    only:
        - master

cache:
    directories:
        - $HOME/.gradle

before_install:
    - git submodule update --init --recursive

before_script:
    - mysql -e 'CREATE DATABASE Sisyphus CHARACTER SET = utf8;'
    - gradle flywayMigrate -Pflyway.url=jdbc:mysql://127.0.0.1:3306/Sisyphus -Pflyway.user=travis -x testClasses

script:
    - gradle check -Dspring.profiles.active=travis -x classes
